INSERT INTO jokes (type, setup, punchline) VALUES
                                               ('dad', 'Why don’t eggs tell jokes?', 'Because they’d crack each other up.'),
                                               ('school', 'Why was the math book sad?', 'Because it had too many problems.'),
                                               ('animal', 'What do you call a fish wearing a bowtie?', 'Sofishticated.'),
                                               ('tech', 'Why did the computer show up at work late?', 'It had a hard drive.'),
                                               ('pun', 'I only know 25 letters of the alphabet.', 'I don’t know y.'),
                                               ('programming', 'Why do Java developers wear glasses?', 'Because they don’t C#!'),
                                               ('tech', 'Why did the programmer quit his job?', 'Because he didn’t get arrays.'),
                                               ('pun', 'I told my computer I needed a break.', 'Now it won’t stop sending me KitKats.'),
                                               ('dad', 'Why don’t skeletons fight each other?', 'They don’t have the guts.'),
                                               ('animal', 'Why did the scarecrow win an award?', 'Because he was outstanding in his field.'),
                                               ('school', 'Why was the math book sad?', 'Because it had too many problems.'),
                                               ('science', 'Why can’t you trust atoms?', 'Because they make up everything.'),
                                               ('work', 'Why did the coffee file a police report?', 'It got mugged.'),
                                               ('life', 'I’m reading a book on anti-gravity.', 'It’s impossible to put down.'),
                                               ('tech', 'Why did the computer show up late?', 'It had a hard drive.'),
                                               ('programming', 'What is a programmer’s favorite hangout place?', 'The Foo Bar.'),
                                               ('dad', 'Why don’t scientists trust atoms?', 'Because they make up everything!'),
                                               ('programming', 'Why do programmers prefer dark mode?', 'Because the light attracts bugs.'),
                                               ('tech', 'Why did the developer go broke?', 'Because he used up all his cache.'),
                                               ('pun', 'Why can’t your nose be 12 inches long?', 'Because then it would be a foot.'),
                                               ('animal', 'What do you call a bear with no teeth?', 'A gummy bear.'),
                                               ('science', 'Why can’t you trust atoms?', 'Because they make up everything.'),
                                               ('school', 'Why was the math book sad?', 'Because it had too many problems.'),
                                               ('dad', 'Why did the scarecrow win an award?', 'Because he was outstanding in his field.'),
                                               ('work', 'Why did the coffee file a police report?', 'It got mugged.'),
                                               ('life', 'What do you call fake spaghetti?', 'An impasta.'),
                                               ('programming', 'What is a programmer’s favorite hangout place?', 'The Foo Bar.'),
                                               ('tech', 'Why did the computer go to the doctor?', 'It had a virus.'),
                                               ('pun', 'What did one wall say to the other?', 'I’ll meet you at the corner.'),
                                               ('dad', 'Why don’t eggs tell jokes?', 'Because they’d crack each other up.'),
                                               ('animal', 'Why do cows have hooves instead of feet?', 'Because they lactose.'),
                                               ('science', 'Why did the physics professor break up with the biology professor?', 'There was no chemistry.'),
                                               ('school', 'What did the pencil say to the paper?', 'I dot my i’s on you.'),
                                               ('life', 'Why did the bicycle fall over?', 'Because it was two-tired.'),
                                               ('programming', 'Why do Java developers wear glasses?', 'Because they don’t C#.'),
                                               ('tech', 'Why was the computer cold?', 'Because it left its Windows open.'),
                                               ('pun', 'Why did the tomato turn red?', 'Because it saw the salad dressing.'),
                                               ('dad', 'How do you organize a space party?', 'You planet.'),
                                               ('animal', 'What do you get from a pampered cow?', 'Spoiled milk.'),
                                               ('science', 'Why are ghosts bad at lying?', 'Because they are too transparent.'),
                                               ('school', 'What’s a math teacher’s favorite place in NYC?', 'Times Square.'),
                                               ('life', 'What do you call a lazy kangaroo?', 'A pouch potato.'),
                                               ('programming', 'Why did the function return early?', 'Because it had a base case.'),
                                               ('tech', 'Why did the PowerPoint Presentation cross the road?', 'To get to the other slide.'),
                                               ('pun', 'What did the Atlantic Ocean say to the United States?', 'Nothing, it just waved.'),
                                               ('dad', 'Why did the man put his money in the freezer?', 'He wanted cold hard cash.'),
                                               ('animal', 'Why did the cat sit on the computer?', 'To keep an eye on the mouse.'),
                                               ('science', 'Why did the mitochondria break up with the nucleus?', 'It needed more space.'),
                                               ('school', 'What did the student say after a graphing test?', 'That was off the charts!'),
                                               ('life', 'Why don’t skeletons fight each other?', 'They don’t have the guts.'),
                                               ('programming', 'Why do programmers hate nature?', 'It has too many bugs.'),
                                               ('tech', 'Why was the smartphone acting so childish?', 'Because it lost its SIM card.'),
                                               ('pun', 'Why did the cookie go to the doctor?', 'Because it felt crummy.'),
                                               ('dad', 'Why did the golfer bring an extra pair of pants?', 'In case he got a hole in one.'),
                                               ('animal', 'Why can’t you trust a duck with a secret?', 'Because they quack under pressure.'),
                                               ('science', 'Why did the nucleus get invited to the party?', 'Because it’s the life of the cell.'),
                                               ('school', 'Why did the teacher wear sunglasses?', 'Because her students were so bright.'),
                                               ('life', 'Why don’t some couples go to the gym?', 'Because some relationships don’t work out.'),
                                               ('programming', 'Why did the coder get kicked out of school?', 'Because he had class issues.'),
                                               ('tech', 'Why can’t a computer take its hat off?', 'Because it has a bad case of CAPS LOCK.'),
                                               ('pun', 'Why don’t oysters donate to charity?', 'Because they are shellfish.'),
                                               ('dad', 'What do you call cheese that isn’t yours?', 'Nacho cheese.'),
                                               ('animal', 'Why did the dog sit in the shade?', 'Because he didn’t want to be a hot dog.'),
                                               ('science', 'Why don’t you ever trust stairs?', 'Because they’re always up to something.'),
                                               ('school', 'Why did the kid bring a ladder to school?', 'Because he wanted to go to high school.'),
                                               ('programming', 'Why did the backend developer leave the restaurant?', 'Because the table was full.'),
                                               ('tech', 'Why did the web developer go broke?', 'Because he used up all his cache.'),
                                               ('pun', 'What did the fish say when it hit the wall?', 'Dam.'),
                                               ('dad', 'Why did the dad joke fail?', 'Because it was too pun-ishing.'),
                                               ('animal', 'Why don’t elephants use computers?', 'Because they’re afraid of the mouse.'),
                                               ('science', 'What does a physicist say when meditating?', 'Ohm...'),
                                               ('school', 'Why did the student eat his homework?', 'Because the teacher told him it was a piece of cake.'),
                                               ('life', 'Why do we never tell secrets on a farm?', 'Because the potatoes have eyes and the corn has ears.'),
                                               ('work', 'Why don’t we tell jokes at the office?', 'Because they don’t work.'),
                                               ('programming', 'Why do Python developers wear glasses?', 'Because they can’t C.'),
                                               ('tech', 'Why did the computer keep sneezing?', 'It had a bad case of Windows.'),
                                               ('pun', 'Why did the chicken join a band?', 'Because it had the drumsticks.'),
                                               ('dad', 'What time did the man go to the dentist?', 'Tooth-hurty.'),
                                               ('animal', 'Why can’t leopards play hide and seek?', 'Because they’re always spotted.'),
                                               ('science', 'Why did the germ go to space?', 'To find a new world to infect.'),
                                               ('school', 'Why was the music teacher arrested?', 'Because she got caught with too many notes.'),
                                               ('life', 'Why don’t some people trust stairs?', 'They’re always up to something.'),
                                               ('work', 'Why did the employee get fired from the orange juice factory?', 'Lack of concentration.'),
                                               ('programming', 'Why do developers hate meetings?', 'Because they interrupt their loops.'),
                                               ('tech', 'Why don’t robots ever get scared?', 'Because they have nerves of steel.'),
                                               ('pun', 'How does a penguin build its house?', 'Igloos it together.'),
                                               ('dad', 'Why did the man put sugar on his pillow?', 'So he could have sweet dreams.'),
                                               ('animal', 'What do you call an alligator in a vest?', 'An investigator.'),
                                               ('science', 'Why don’t you ever trust atoms?', 'They make up everything.'),
                                               ('school', 'Why did the teacher write on the window?', 'Because she wanted the lesson to be clear.'),
                                               ('life', 'Why did the man run around his bed?', 'Because he was trying to catch up on sleep.'),
                                               ('work', 'Why was the calendar afraid?', 'Because its days were numbered.'),
                                               ('programming', 'Why did the array go to therapy?', 'It had too many issues.'),
                                               ('tech', 'Why was the keyboard always relaxed?', 'Because it had all the right keys.'),
                                               ('pun', 'What do you call a fake noodle?', 'An impasta.'),
                                               ('dad', 'How do you make holy water?', 'You boil the hell out of it.'),
                                               ('animal', 'Why did the frog take the bus?', 'Because his car got toad.'),
                                               ('science', 'Why did the chemist read a book on helium?', 'Because he couldn’t put it down.'),
                                               ('school', 'Why was the student’s report card wet?', 'It was below C level.'),
                                               ('life', 'Why can’t your nose be 12 inches long?', 'Because then it’d be a foot.'),
                                               ('work', 'Why did the office worker always carry a ladder?', 'To climb the corporate ladder.'),
                                               ('programming', 'Why did the programmer get lost in the forest?', 'Because he used the wrong tree structure.'),
                                               ('tech', 'Why was the IT guy at the beach?', 'To surf the web.'),
                                               ('pun', 'What happens to a frog’s car when it breaks down?', 'It gets toad away.'),
                                               ('dad', 'What do you call a group of musical whales?', 'An orca-stra.'),
                                               ('animal', 'What do cows do for fun?', 'Go to the mooo-vies.'),
                                               ('science', 'Why can’t you trust the periodic table?', 'Because it’s full of suspicious elements.'),
                                               ('school', 'Why did the teacher go to jail?', 'Because she was caught in a class action.'),
                                               ('life', 'Why don’t some couples go to the gym?', 'Because some relationships don’t work out.'),
                                               ('work', 'Why did the boss bring a ladder to the meeting?', 'To take things to the next level.'),
                                               ('programming', 'Why did the coder sleep under his desk?', 'Because he had a tight deadline.'),
                                               ('tech', 'Why did the smartphone need glasses?', 'Because it lost its contacts.'),
                                               ('pun', 'Why was the graveyard so noisy?', 'Because of all the coffin.'),
                                               ('dad', 'Why did the man bring a pencil to the party?', 'Because he wanted to draw attention.');
